Repository longshaww/RentApartmentClient, pull requests merged in 2022-04, with the labels that each got.

#3 client improvement resolve #2
  src/components/Navbar.tsx
  src/feature/Detail/components/CardDetail.tsx
  src/feature/Detail/components/CardRoom.tsx
  src/feature/Detail/pages/Detail.tsx
  src/feature/Home/components/CardHome.tsx
Labels: enhancement, good first issue

#5 apartment detail resolve #4
  package-lock.json
  package.json
  src/assets/css/apartment.detail.scss
  src/components/Navbar.tsx
  src/feature/Detail/components/CardRoom.tsx
Labels: enhancement, good first issue

#6 reservation interface design done
  src/App.tsx
  src/assets/css/info.scss
  src/components/Navbar.tsx
  src/feature/Info/components/ConfirmButton.tsx
  src/feature/Info/components/PolycyCancel.tsx
  src/feature/Info/components/Preferential.tsx
  src/feature/Info/components/PriceDetails.tsx
  src/feature/Info/components/Requirement.tsx
  src/feature/Info/components/RoomInfo.tsx
  src/feature/Info/components/TitleInfo.tsx
  src/feature/Info/components/YourInfo.tsx
  src/feature/Info/pages/InfoCustomer.tsx
Labels: enhancement, help wanted, good first issue

#8 billing dev resolve #7
  package-lock.json
  package.json
  src/App.tsx
  src/assets/css/app.scss
  src/components/Navbar.tsx
  src/feature/Detail/components/CardRoom.tsx
  src/feature/Detail/pages/Detail.tsx
  src/feature/Home/components/CardHome.tsx
  src/feature/Home/components/Search.tsx
  src/feature/Info/components/PolicyCancel.tsx
  src/feature/Info/components/PolycyCancel.tsx
  src/feature/Info/pages/InfoCustomer.tsx
  src/feature/Info/pages/booking.tsx
  src/reducers/detail.lessor.tsx
Labels: enhancement, help wanted, good first issue

#10 DateTime issues resolve #9
  src/actions/date.choosen.tsx
  src/actions/detail.apartment.tsx
  src/actions/lessor.tsx
  src/constant/constant.tsx
  src/container/global.state.action.js
  src/feature/Detail/components/CardDetail.tsx
  src/feature/Detail/components/CardRoom.tsx
  src/feature/Home/components/CardHome.tsx
  src/feature/Home/components/Search.tsx
  src/feature/Info/components/PriceDetails.tsx
  src/feature/Info/components/RoomInfo.tsx
  src/reducers/date.choosen.tsx
  src/reducers/detail.apartment.tsx
  src/reducers/index.tsx
  src/reducers/lessor.tsx
Labels: documentation, enhancement, good first issue

#12 sprint2 client resolve #11
  package-lock.json
  package.json
  src/actions/bill.information.tsx
  src/constant/constant.tsx
  src/feature/Info/components/ConfirmButton.tsx
  src/feature/Info/components/PolicyCancel.tsx
  src/feature/Info/components/PriceDetails.tsx
  src/feature/Info/components/Requirement.tsx
  src/feature/Info/components/YourInfo.tsx
  src/feature/Info/components/information.form.tsx
  src/feature/Info/pages/booking.tsx
  src/reducers/bill.information.tsx
  src/reducers/index.tsx
Labels: SweetAlert, React, TypeScript

#16 datetime resolve #15
  src/App.css
  src/App.tsx
  src/components/AnimatedRoutes.tsx
  src/feature/Detail/components/CardDetail.tsx
  src/feature/Info/components/information.form.tsx
  src/logo.svg
Labels: Api, SweetAlert, React, TypeScript
